### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by martin-sweeny** [Mikaela/pgp-alt-wot#1]
I was reading the readme, and noticed the following link is dead:
https://www.jonaharagon.com/verify/

**Comment by Mikaela** [comment]
Thank you for the report.

@jonaharagon Do you have any replacement for your verify page? I am linking there in [this repo's README.md](https://github.com/Mikaela/pgp-alt-wot#places-to-check-for-keys)

* * * * *

*Issues are enabled on GitHub by accident and after resolving this I will be disabling the tracker.*

**Comment by Mikaela** [comment]
It seems to have gotten removed in https://github.com/jonaharagon/www.jonaharagon.com/commit/d7b0a1082ece9e3d018037a3c7df58f6502cdd2e#diff-3c748bda8a0e1d67799dc051b1277a9de0dbf10719ad1d0b4612f9fca125854c and maybe that was intentional and it won't be returning.
